import {
  Baby,
  Building2,
  CheckCircle2,
  CornerUpRight,
  Droplets,
  FileCheck,
  Gem,
  Home,
  LandPlot,
  Lightbulb,
  MapPin,
  Route,
  ShieldCheck,
  Trees,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  'shield': ShieldCheck,
  'shield-check': ShieldCheck,
  'file-check': FileCheck,
  'land-plot': LandPlot,
  'building': Building2,
  'trees': Trees,
  'home': Home,
  'route': Route,
  'lightbulb': Lightbulb,
  'baby': Baby,
  'users': Users,
  'droplets': Droplets,
  'zap': Zap,
  'gem': Gem,
  'corner': CornerUpRight,
  'map-pin': MapPin,
  'check': CheckCircle2,
}
